### PR TITLE
Refactor and improve testing

### LINKED ISSUE #63: Add tests for integration code
It is hard to add unit tests for integration code, which currently is only tested in the wild, but this path should be refactored as much as possible to add proper testing.

### PR DESCRIPTION
**Pull request by Enchufa2**
Closes #63 

With this PR, I've meticulously refactored the integration code to add tests, and probably solved some issues in the process. We have a pretty good coverage of that part now, but also I've added specific tests "in the wild" with the r2u image, so that we are pretty confident from now on that new releases do not break existing infrastructure. 

So far, I've added tests for edge cases that failed in the past: a installation (1) from GitHub, (2) of a Bioc package, (3) of a binary package from r-universe. @eddelbuettel please check the `tests/r2u.sh` file, and let me know if you'd like to add any other tests.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
(Only looked at that script so far)  

That looks very promising.  Do you have a mock somewhere else in the tests for "version X available as binary but X+1 from source" ?  This is something that bit us again at work this week with a new CRAN release and the slight wait for an r2u update. I guess build from source is our fallback though the beauty of r2u is to not require source tool installation so a simply switch may fail.  

Another thing to try is maybe with littler installBioc.r (which need BiocManager first).

**Comment by Enchufa2** [comment]
> That looks very promising. Do you have a mock somewhere else in the tests for "version X available as binary but X+1 from source" ? 

Yes! I do have mocks for this case and others, so it should be covered.

> Another thing to try is maybe with littler installBioc.r (which need BiocManager first).

But installBioc.r is not in the PATH in the r2u image. Is that intended?

**Comment by Enchufa2** [comment]
> But installBioc.r is not in the PATH in the r2u image. Is that intended?

Maybe because installBioc.r installs from source?

**Comment by eddelbuettel** [comment]
Yes, I assumed you had that covered.

`installBioc.r` is one of those many other tools in `littler` that are not in the path, but sometimes brought up by eager users on the Rocker repo or other places.  Feel free to skip then.

The script is good. We have a place to add more regressions and corner cases as we go forward.  (Also: tiledbsoma is Yuge.  Maybe we want to test r-universe with something smaller?  I think I have some smaller things on GH-yet-not-at-CRAN as eg [RcppKalman](https://eddelbuettel.r-universe.dev/RcppKalman).  But you can of course keep testing with tiledbsoma, it will remain under active development.)

**Comment by Enchufa2** [comment]
Good point. I'll switch to RcppKalman then.

**Pull request merged**
