### PR TITLE
Adding debian package files

### PR DESCRIPTION
**Pull request by eddelbuettel**
This is what I had done last week when I built the first containers (but just rebased to your main branch now).  Feel free to integrate it, or skip it.

The main upside for me is that if and when `bspm` is a proper package, we can access `/usr` with new files as all such additions can be undone cleanly.  I will not copy directly into `/usr` which is almost always a bad idea.

Got a little distracted from `bspm` work but hope to get back to it.

### CODE REVIEW

**Comment by Enchufa2** [comment]
Thanks. Please, add the `debian` directory to `.Rbuildignore`.

`bspm` has been sitting on CRAN's newbies queue for a week now. I'll wait to merge this until we receive news from CRAN.

**Comment by eddelbuettel** [comment]
> Thanks. Please, add the debian directory to .Rbuildignore.

Doh. Of course.

> I'll wait to merge this until we receive news from CRAN.

Sure.  My `tiledb` package (from work) has been idling there for three weeks.  Not good.

**Comment by Enchufa2** [comment]
Thanks again!

**Comment by eddelbuettel** [comment]
No problem -- and _Thank You!_ for writing this!  Lemme know if you need a hand with Debian stuff in GitHub Actions or whatnot.

**Pull request merged**
